"use client";
import { useState } from "react";
import PageHeader from "@/components/PageHeader";
import { DataState, MetricBand, PathDistribution } from "@/components/Telemetry";
import RequestTimeseries from "@/components/RequestTimeseries";
import { api } from "@/lib/api";
import { useScopedData } from "@/lib/useScopedData";
export default function AnalyticsPage() {
  const [refresh, setRefresh] = useState(0);
  const overview = useScopedData(api.getOverview, refresh);
  const series = useScopedData(api.getTimeseries, refresh);
  const models = useScopedData(api.getModelMetrics, refresh);
  return <div><PageHeader index="02 / Analytics" title="Cache Efficiency & Economic Impact" description="Observed traffic and estimated savings. No synthetic history or projected performance." action={<button className="btn-secondary" onClick={() => setRefresh(v => v + 1)}>Refresh</button>} />{overview.data ? <MetricBand data={overview.data} /> : <DataState loading={overview.loading} error={overview.error} retry={() => setRefresh(v => v + 1)} />}<section className="hairline-panel mb-6"><div className="panel-heading">Cache effectiveness / time<span className="text-on-surface-faint">24 observed buckets</span></div>{series.loading || series.error ? <DataState loading={series.loading} error={series.error} /> : series.data?.some(p => p.total_requests > 0) ? <RequestTimeseries points={series.data} /> : <DataState empty />}</section><div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">{overview.data && <><PathDistribution data={overview.data} /><section className="hairline-panel"><div className="panel-heading">Latency measurements</div><div className="state-panel"><div className="label-caps">Average cache lookup</div><div className="metric-value">{overview.data.total_requests ? `${overview.data.avg_cache_lookup_ms.toFixed(2)} ms` : "—"}</div><div className="label-caps">Average upstream latency</div><div className="metric-value">{overview.data.misses ? `${overview.data.avg_upstream_latency_ms.toFixed(2)} ms` : "—"}</div></div></section></>}</div><section className="hairline-panel"><div className="panel-heading">Model / provider breakdown</div>{models.loading || models.error ? <DataState loading={models.loading} error={models.error} /> : !models.data?.length ? <DataState empty /> : <div className="overflow-x-auto"><table className="data-table"><thead className="table-header-row"><tr>{["Model", "Provider", "Requests", "Hit rate", "Est. savings", "Avg. latency"].map(label => <th className="table-header-cell" key={label}>{label}</th>)}</tr></thead><tbody>{models.data.map(row => <tr key={`${row.model}/${row.provider}`}><td>{row.model}</td><td>{row.provider}</td><td>{row.total_requests}</td><td>{row.hit_rate_pct.toFixed(2)}%</td><td>${row.cost_saved_usd.toFixed(4)}</td><td>{row.avg_latency_ms.toFixed(2)} ms</td></tr>)}</tbody></table></div>}</section></div>;
}
